# Generated by Django 5.1.2 on 2024-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час додавання')),
            ],
            options={
                'verbose_name': 'Консультація',
                'verbose_name_plural': 'Консультації',
                'db_table': 'consultation',
            },
        ),
    ]
